### ISSUE TITLE
Refactoring and setup of test environment

### ISSUE THREAD

**Issue by k00ni** [AKSW/cubevizjs#5]
Let us collect all task here, which are required to make a good refactoring and establish a sufficient test environment.

**TODO** (please complete/adapt):
- [x] Setup test environment (unit testing with mocha)
- [x] Better code styling?
- [x] Refactor Specifications (e.g. cube containing one dimension with one dimension element? etc...), Rules (collection of specifications, e.g. heatmap rule)
- [x] Establish consequent uni directional data flow (currently not present everywhere)
